server:
  port: 8082

spring:
  application:
    name: lt-demo
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:cn/**/mapper/*.xml

logging:
  level:
    root: info
    cn.njust.label: debug
host:
  mall:
    admin: http://localhost:8080